# Site settings
title: Emily Josephs
email: 
description: > # this means to ignore newlines until "baseurl:"
  Website for Emily Josephs
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://emjosephs.github.io" # the base hostname & protocol for your site
twitter_username: emjosephs
github_username: emjosephs

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
